---
title: "Oligo binned proportions"
author: "G Sejourne"
date: "2026-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggsci)
library(readxl) 
library(tidyverse)
library(dplyr)
```

```{r}
# data formatting
# read in quPath cell data
setwd(getwd())
df <- read.csv("./DATA/ASPA_Pdgfra_Celldata_20260406.csv")
df$Image <- substr(df$Image, 5, nchar(df$Image))

dimensions <- read.csv("DATA/ASPA_heights_widths.csv")
dimensions$Image <- substr(dimensions$Image, 5, nchar(dimensions$Image))

# extract genotype information and rename columns (swap out for alternative method of getting genotypes as needed)
df <- df %>%
  mutate(
    animal = str_extract(Image, "_\\d{6}_") %>%
                str_replace_all("_", ""),
    sex = str_extract(Image, "_[FM]_") %>%
             str_replace_all("_", ""),
    genotype = str_extract(Image, "_(WT|KO)_") %>% 
      str_replace_all("_", "")
  )

colnames(df)[4] <- 'Centroid.Y'

# mutate dataframe to split the column into 10 equally sized bins based on Y-coordinate (Y_max is the centroid.Y of the cell closest to the bottom of the image so we assume this is approximately equal to image height)
df <- df %>%
  group_by(Image) %>%
  mutate(
    Y_max = max(Centroid.Y, na.rm = TRUE),
    Y_norm = Centroid.Y / Y_max,
    bin = case_when(
    Y_norm >= 0 & Y_norm <= 0.25 ~ 1,
    Y_norm > 0.25 & Y_norm <= 0.5 ~ 2,
    Y_norm > 0.5 & Y_norm <= 0.75 ~ 3,
    Y_norm > 0.75 & Y_norm <=  1.0 ~ 4
  )
  ) %>%
  ungroup()

# exclude images filtered out by QC
exclude_animals = c("551834", "551932", "551933", "551935")
df <- df[!(df$animal %in% exclude_animals),]

# save binned data as a csv in case you want to feed it into another analysis pipeline or graphpad prism
write.csv(df, "./DATA/oligo_layers_raw.csv", row.names = FALSE)

print(df)
print(unique(df$Image))
print(unique(df$animal))

```


```{r}
# Assume df has columns: Image, Class
# First, get unique image IDs
unique_images <- unique(df$Image)

# Create an empty data frame to store results 
df_counts <- data.frame(Image = character(),
                            opc = integer(),
                            mol = integer(),
                            oligo = integer(),
                            int = integer(),
                     stringsAsFactors = FALSE)

# Loop through each image
for (img in unique_images) {

  # Loop through each bin
  for (b in c(1:4)) {
    # Subset the data for the current image
    temp <- df[df$Image == img & df$bin == b, ]
    
    # Count each type in the 'class' column
    opc <- sum(temp$Classification == "ASPA-: Pdgfra+")
    mol <-sum(temp$Classification == "ASPA+: Pdgfra-")
    int <- sum(temp$Classification == "ASPA-: Pdgfra-")
    oligo <- sum(temp$Classification %in% c("ASPA+: Pdgfra+", "ASPA-: Pdgfra+", "ASPA+: Pdgfra-", "ASPA-: Pdgfra-"))
    
    # Append the results to the df_counts data frame
    df_counts <- rbind(df_counts, data.frame(Image = img, bin = b, animal = unique(df[df$Image == img,]$animal), genotype = unique(df[df$Image == img,]$genotype), opc = opc, mol = mol, int = int, oligo = oligo))
  }
  df_counts <- unique(df_counts)
}

# View result
print(df_counts)

# save binned count data as a csv in case you want to feed it into another analysis pipeline or graphpad prism
write.csv(df_props, "./DATA/oligo_binned_proportions.csv", row.names = FALSE)
```

```{r}
# animal averages (counts per bin)
df_counts_totals <- df_counts %>%
  group_by(genotype, animal, bin) %>%
  summarise(opc = sum(opc),
            mol = sum(mol), 
            int = sum(int), 
            oligo = sum(oligo),
            .groups = "drop")

print(df_counts_totals)

# save binned animal means count data as a csv in case you want to feed it into another analysis pipeline or graphpad prism
write.csv(df_counts_totals, "./DATA/oligo_binned_proportions_totals.csv", row.names = FALSE)
```
